### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by awsp** [awsp/d3-awsp-timeline#21]
## Todo
- [x] Resize the current dimension
- [x] Add horizontal guideline 
- [ ] Implement brush to zoom in / out
- [ ] Add more events handler such as (double click, click, etc.)
- [ ] Show/Hide rows
- [ ] Better error handling
- [ ] Jasmine testing
